version: "3.5"
version: "3.5"

services:
  mongodb:
    image: mongo:latest
    # container_name: nest_mongodb
    environment:
      - MONGODB_DATABASE="Messenger"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container_messenger:/data/db

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-docker-app-messenger
  #   environment:
  #     - PORT=${PORT}
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - ./:/app

volumes:
  mongodb_data_container_messenger:
