version: "3.5"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="Messenger"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container_messenger:/data/db

<<<<<<< HEAD
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-docker-app-messenger
  #   environment:
  #     - PORT=${PORT}
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - ./:/app
=======
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-app-messenger
    environment:
      - PORT=${PORT}
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./:/app
>>>>>>> 5e553e57e490483e319f607598792c2ab841dca2

volumes:
  mongodb_data_container_messenger:
